# kubeadm init --pod-network-cidr=10.17.0.0/16 --service-cidr=10.18.0.0/24 --service-dns-domain=cluster.local
# kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

# kubeadm join 10.1.2.1:6443 --token mf6m14.bcg03u44em42reb4 \
#    --discovery-token-ca-cert-hash sha256:3bf3e8f6e29814bf4eb39db5780ea32d672d828f3bf02d7de1ba190c260d32d4

# - set_fact:
#     string_to_echo: "{{ command_output.stdout }}"

# - name: get join command
#   command: "kubeadm token create --print-join-command"
#   delegate_to: "{{ groups['master'][0] }}"
#   register: join_output
  # with_items: "{{ groups['master'][0] }}"

# - name: store join command as variable
#   set_fact:
#     string_to_echo: "{{ join_output.stdout }}"

- debug:
    var: join_output.stdout

  #     delegate_to: "{{ item }}"
  #     delegate_facts: true
  #     when: hostvars[item]['ansible_default_ipv4'] is not defined
  #     with_items: "{{ groups['etcd'] }}"

- name: Run join command
  shell:
    cmd: "{{ join_output.stdout }}"
